#!/bin/bash
# Build and install Yersinia with GTK support

cd /opt
sudo git clone https://github.com/tomac/yersinia.git
cd yersinia
sudo ./autogen.sh
sudo ./configure --with-gtk
sudo make
sudo make install
